Windows Server 2019 Gthub with RDP Access (ngrok US) Languages Disclaimer- THIS RDP IS WORK FOR 6 HOURS PowerShed 100 0' Create a free VPS with 2cpu-7gb Ram FREE with Github: •Click Fork in the right corner of the screen to save it to your Github. Visit https//dashboard ngrok.com to get NGROKAUTH_TOKEN in Github go to Settings» Secrets New repository secret ·加Namenter NCROKAUTLTOKEN *in Value: visit httpsildashboard ngrokcom/auth/yourauthtoken Copy and Paste Your Authtoken into •Press Add secret .Go to Action henils,owner Run workflow Reload the page and press henil isowner> build •Press the down arow of Assign User on Connect To Your RPD to get User, Password •if you want see a video how to get rdp for 6 hoursi giving a lnkc- htps/lyoutu be/UCUvYXo,GO enjoy# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
